[core.data_output_options]
out_continuous_file_name = "all_continuous_data.nc"
out_final_file_name = "final_state.nc"
out_initial_file_name = "initial_state.nc"
out_merge_file_name = "ve_full_model_configuration.toml"
out_path = "/tmp/ve_example/out"
save_continuous_data = true
save_final_state = true
save_initial_state = true
save_merged_config = true

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_climate_data.nc"
var_name = "air_temperature_ref"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_climate_data.nc"
var_name = "relative_humidity_ref"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_climate_data.nc"
var_name = "atmospheric_pressure_ref"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_climate_data.nc"
var_name = "precipitation"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_climate_data.nc"
var_name = "atmospheric_co2_ref"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_climate_data.nc"
var_name = "mean_annual_temperature"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_climate_data.nc"
var_name = "wind_speed_ref"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_elevation_data.nc"
var_name = "elevation"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_surface_runoff_data.nc"
var_name = "surface_runoff"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_soil_data.nc"
var_name = "pH"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_soil_data.nc"
var_name = "bulk_density"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_soil_data.nc"
var_name = "clay_fraction"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_lmwc"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_maom"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_microbe"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_pom"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_soil_data.nc"
var_name = "soil_c_pool_necromass"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_soil_data.nc"
var_name = "soil_enzyme_pom"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_soil_data.nc"
var_name = "soil_enzyme_maom"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_litter_data.nc"
var_name = "litter_pool_above_metabolic"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_litter_data.nc"
var_name = "litter_pool_above_structural"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_litter_data.nc"
var_name = "litter_pool_woody"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_litter_data.nc"
var_name = "litter_pool_below_metabolic"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_litter_data.nc"
var_name = "litter_pool_below_structural"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_litter_data.nc"
var_name = "lignin_above_structural"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_litter_data.nc"
var_name = "lignin_woody"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_litter_data.nc"
var_name = "lignin_below_structural"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_plant_data.nc"
var_name = "plant_cohorts_n"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_plant_data.nc"
var_name = "plant_cohorts_pft"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_plant_data.nc"
var_name = "plant_cohorts_cell_id"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_plant_data.nc"
var_name = "plant_cohorts_dbh"

[[core.data.variable]]
file_path = "/private/tmp/ve_example/data/example_plant_data.nc"
var_name = "downward_shortwave_radiation"

[core.grid]
cell_area = 8100
cell_nx = 9
cell_ny = 9
grid_type = "square"
xoff = -45.0
yoff = -45.0

[core.timing]
run_length = "2 years"
start_date = "2013-01-01"
update_interval = "1 month"

[core.layers]
above_canopy_height_offset = 2.0
canopy_layers = 10
soil_layers = [
  -0.25,
  -1.0,
]
subcanopy_layer_height = 1.5
surface_layer_height = 0.1

[hydrology]
initial_groundwater_saturation = 0.9
initial_soil_moisture = 0.5

[abiotic_simple]

[[animal.functional_groups]]
adult_mass = 1.0
birth_mass = 0.1
development_status = "adult"
development_type = "direct"
diet = "carnivore"
excretion_type = "uricotelic"
metabolic_type = "endothermic"
name = "carnivorous_bird"
offspring_functional_group = "carnivorous_bird"
reproductive_type = "iteroparous"
taxa = "bird"

[[animal.functional_groups]]
adult_mass = 0.5
birth_mass = 0.05
development_status = "adult"
development_type = "direct"
diet = "herbivore"
excretion_type = "uricotelic"
metabolic_type = "endothermic"
name = "herbivorous_bird"
offspring_functional_group = "herbivorous_bird"
reproductive_type = "iteroparous"
taxa = "bird"

[[animal.functional_groups]]
adult_mass = 40.0
birth_mass = 4.0
development_status = "adult"
development_type = "direct"
diet = "carnivore"
excretion_type = "ureotelic"
metabolic_type = "endothermic"
name = "carnivorous_mammal"
offspring_functional_group = "carnivorous_mammal"
reproductive_type = "iteroparous"
taxa = "mammal"

[[animal.functional_groups]]
adult_mass = 10.0
birth_mass = 1.0
development_status = "adult"
development_type = "direct"
diet = "herbivore"
excretion_type = "ureotelic"
metabolic_type = "endothermic"
name = "herbivorous_mammal"
offspring_functional_group = "herbivorous_mammal"
reproductive_type = "iteroparous"
taxa = "mammal"

[[animal.functional_groups]]
adult_mass = 0.01
birth_mass = 0.001
development_status = "adult"
development_type = "direct"
diet = "carnivore"
excretion_type = "uricotelic"
metabolic_type = "ectothermic"
name = "carnivorous_insect"
offspring_functional_group = "carnivorous_insect"
reproductive_type = "iteroparous"
taxa = "insect"

[[animal.functional_groups]]
adult_mass = 0.005
birth_mass = 0.0005
development_status = "adult"
development_type = "direct"
diet = "herbivore"
excretion_type = "uricotelic"
metabolic_type = "ectothermic"
name = "herbivorous_insect"
offspring_functional_group = "herbivorous_insect"
reproductive_type = "semelparous"
taxa = "insect"

[[animal.functional_groups]]
adult_mass = 0.005
birth_mass = 0.0005
development_status = "adult"
development_type = "indirect"
diet = "herbivore"
excretion_type = "uricotelic"
metabolic_type = "ectothermic"
name = "butterfly"
offspring_functional_group = "caterpillar"
reproductive_type = "semelparous"
taxa = "insect"

[[animal.functional_groups]]
adult_mass = 0.005
birth_mass = 0.0005
development_status = "larval"
development_type = "indirect"
diet = "herbivore"
excretion_type = "uricotelic"
metabolic_type = "ectothermic"
name = "caterpillar"
offspring_functional_group = "butterfly"
reproductive_type = "nonreproductive"
taxa = "insect"

[plants]
a_plant_integer = 12
ftypes = [
  {pft_name = "shrub", max_height = 1.0},
  {pft_name = "broadleaf", max_height = 50.0},
]
